### ISSUE TITLE
GITM binaries

### ISSUE THREAD

**Issue by SuLFC** [aaronjridley/GITM#2]
When I am running: example_**gitm_cindi_plot_script.py**, it is asking for: **List of input GITM binaries**. Where can I find these GITM binaries?
Thanks

**Comment by aaronjridley** [comment]
Not sure that I understand.  Did you do a run of GITM?  This code takes GITM output files (after the code is run - the 3DALL files) and compares them to the CINDI instrument data, so the run needs to be during the time periods in which CINDI has valid data also. Hope that helps.

**Comment by SuLFC** [comment]
Where can I find the GITM binaries from the GITHUB master?

**Comment by aaronjridley** [comment]
The GITM binaries are produced by running the code.  The binaries don't exist until you run the code - they are the output from the model.

**Comment by SuLFC** [comment]
I have run the **gitm.py** file and it generated  **OMNI_OMNI2_merged_20120213-v1.cdf**  but am unable to specify or find the **following** when i run **_gitm_cindi_plot_script.py**

filename = raw_input('Output image file (eg Test.png): ')
**gitmlist = raw_input('List of input GITM binaries: ')**
gitmtype = raw_input('GITM binary type (3D, 2D, 1D): ')
**gitmmag = raw_input('Name of GITM 3DMAG or 3DION file: ')**
**cindilist = raw_input('List of input CINDI text files: ')**
match = raw_input('Satellite-Model match method (nearest, average, median): ')
**ykey = raw_input('GITM key of the dependent variable: ')**
title = raw_input('Plot title: ')
Kindly help me on this matter

**Comment by aaronjridley** [comment]
Once again, I have to ask - have you run GITM yet? gitm.py is not GITM - it is a python code that allows the plotting of GITM data files.  Have you compiled the code or configured the code?
