### ISSUE TITLE
Regarding Run-on-Request of GITM

### ISSUE THREAD

**Issue by SuLFC** [aaronjridley/GITM#4]
Sir,
     In the CCMC web page, I find that under Run on Request, the End Year given is 2016. What should I do in order to run the model from 2017 onwards?
     Kindly guide me on this matter. Thanking you.

**Comment by jmbell42** [comment]
This is most likely a limitation put on the request web page by the CCMC group itself. I would contact them to see if they will enable later runs after 2016.  I would encourage you to contact the CCMC run on request team:  gsfc-ccmc-ror@lists.hq.nasa.gov.
